{{- if .Values.federate.dtls.enabled -}}

{{- if .Values.federate.dtls.tls.issuerRef -}}
{{- if or .Values.federate.dtls.tls.key  .Values.federate.dtls.tls.crt }}
{{- fail "issuerRef and  {crt,key} are mutually exclusive" -}}
{{- end -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "coturn.fullname" . }}"
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
    {{- if .Values.federate.dtls.tls.certificate.labels }}
    {{- toYaml .Values.federate.dtls.tls.certificate.labels | nindent 4}}
    {{- end }}
spec:
  dnsNames:
    {{- toYaml .Values.federate.dtls.tls.certificate.dnsNames | nindent 4 }}
  secretName: coturn-dtls-certificate
  issuerRef:
    {{- toYaml .Values.federate.dtls.tls.issuerRef | nindent 4 }}
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
{{- else if and .Values.federate.dtls.tls.key  .Values.federate.dtls.tls.crt }}
apiVersion: v1
kind: Secret
metadata:
  name: coturn-dtls-certificate
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
type: Opaque
data:
  tls.key: {{ .Values.federate.dtls.tls.key | b64enc }}
  tls.crt: {{ .Values.federate.dtls.tls.crt | b64enc }}
{{- else -}}
{{- fail "must specify tls.key and tls.crt , or tls.issuerRef" -}}
{{- end -}}

{{- end -}}
