{{- if or (not .Values.secrets) (not .Values.secrets.zrestSecrets) }}
{{- fail "TURN authentication secrets are not defined in .Values.secrets.zrestSecrets" }}
{{- else if eq (len .Values.secrets.zrestSecrets) 0 }}
{{- fail "At least one authentication secret must be defined" }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: coturn
  labels:
    app: coturn
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  zrest_secret.txt: |
    {{- range .Values.secrets.zrestSecrets }}{{ . | nindent 4 }}
    {{- end }}
{{- end }}
