---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coturn
  labels:
    app: coturn
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coturn-{{ .Release.Namespace }}
  labels:
    app: coturn
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coturn-{{ .Release.Namespace }}
  labels:
    app: coturn
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: coturn-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: coturn
    namespace: {{ .Release.Namespace }}
