name: CMake

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      # Even though 16.04 and 18.04 are EOL, don't bother supporting cmake on them. Too old to be worth it.
      matrix:
        os: [ 'ubuntu:20.04', 'ubuntu:22.04' ]

    runs-on: ubuntu-latest
    container: ${{ matrix.os }}

    steps:
    # Set env variable or otherwise tzdata package requires interaction
    - uses: actions/checkout@v3
    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      uses: ./.github/workflows/actions/ubuntu-build-deps
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: apps tests
      run: cd examples && ./run_tests.sh
