name: CMake

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-20.04', 'ubuntu-22.04', 'ubuntu-24.04' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/workflows/actions/ubuntu-build-deps
        with:
          SUDO: true

      - name: Configure
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Compile
        run: cmake --build build --parallel --config ${{env.BUILD_TYPE}}

      - name: Integration Test
        working-directory: examples
        run: |
          ./run_tests.sh
          ./run_tests_conf.sh
          ./run_tests_prom.sh
