name: Ubuntu

on:
  push:
    branches: ["master"]
    tags: ["4.*"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    name: build + test
    strategy:
      fail-fast: false
      matrix:
        ver:
          - "16.04"
          - "18.04"
          - "20.04"
          - "22.04"
    runs-on: ubuntu-latest
    container: ubuntu:${{ matrix.ver }}
    steps:
      - name: Install Node.js 16 for GitHub Actions
        run: |
          set -ex
          apt update 
          apt install -y wget
          touch "$HOME/.bashrc"
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install 14
        if: ${{ contains('16.04 18.04', matrix.ver) }}

      - uses: actions/checkout@v4
      - name: Install dependencies
        # Set env variable or otherwise `tzdata` package requires interaction.
        env:
          DEBIAN_FRONTEND: noninteractive
        uses: ./.github/workflows/actions/ubuntu-build-deps

      - run: ./configure
      - run: make
      - run: make check

      - run: ./run_tests.sh
        working-directory: examples/
      - run: ./run_tests_conf.sh
        working-directory: examples/
      - run: ./run_tests_prom.sh
        working-directory: examples/
