name: Ubuntu

on:
  push:
    branches: ["master"]
    tags: ["4.*"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    name: build + test
    strategy:
      fail-fast: false
      matrix:
        ver:
          - "16.04"
          - "18.04"
          - "20.04"
          - "22.04"
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.ver }}
      volumes:
        - ${{ contains('16.04 18.04', matrix.ver) && '/node20217:/node20217:rw,rshared' || ' ' }}
        - ${{ contains('16.04 18.04', matrix.ver) && '/node20217:/__e/node20:ro,rshared' || ' ' }}
    steps:
      - name: Install Node.js 20 built against glibc 2.17 for GitHub Actions
        run: |
          set -ex
          apt update 
          apt install -y curl xz-utils
          curl -LO https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
          tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
          ldd /__e/node20/bin/node
        working-directory: /tmp/
        if: ${{ contains('16.04 18.04', matrix.ver) }}

      - uses: actions/checkout@v4
      - name: Install dependencies
        # Set env variable or otherwise `tzdata` package requires interaction.
        env:
          DEBIAN_FRONTEND: noninteractive
        uses: ./.github/workflows/actions/ubuntu-build-deps

      - run: ./configure
      - run: make
      - run: make check

      - run: ./run_tests.sh
        working-directory: examples/
      - run: ./run_tests_conf.sh
        working-directory: examples/
      - run: ./run_tests_prom.sh
        working-directory: examples/
